FROM openjdk:11-jre-slim

ENV H2_VERSION="2.3.232"

ADD "https://repo1.maven.org/maven2/com/h2database/h2/${H2_VERSION}/h2-${H2_VERSION}.jar" /opt/h2.jar

COPY h2.server.properties /root/.h2.server.properties

# Expose the web console port
EXPOSE 8082

# Expose the server port
EXPOSE 9092

ENTRYPOINT ["java","-cp", "/opt/h2.jar","org.h2.tools.Server","-web", "-webDaemon", "-webAllowOthers", "-webPort", "8082","-tcp", "-tcpAllowOthers", "-tcpPort", "9092", "-ifNotExists"]